# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0004_auto_20161210_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
