# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0006_auto_20161216_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_exibicao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'professores',
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['data', 'titulo'], 'verbose_name': 'avaliação', 'verbose_name_plural': 'avaliações'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['disciplina', 'periodo'], 'verbose_name': 'matrícula'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'período'},
        ),
    ]
